"""Build a root-level upload bundle for the dedicated multiplayer service."""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import zipfile

from src.source_loader import game_source


ROOT = Path(__file__).resolve().parent
MARKER = ".killzone-generated-server"


def build_server(output: Path) -> None:
    if output.exists() and any(output.iterdir()):
        marker = output / MARKER
        if not marker.is_file():
            raise RuntimeError(f"Refusing to replace unmarked non-empty directory: {output}")
        shutil.rmtree(output)

    output.mkdir(parents=True, exist_ok=True)
    (output / MARKER).write_text("Generated by build_multiplayer_server.py\n", encoding="utf-8")
    shutil.copy2(ROOT / "multiplayer_server" / "app.py", output / "app.py")
    shutil.copy2(ROOT / "multiplayer_server" / "requirements.txt", output / "requirements.txt")
    (output / "kill_zone.py").write_text(game_source(ROOT), encoding="utf-8", newline="\n")
    (output / "src").mkdir(exist_ok=True)
    shutil.copy2(ROOT / "src" / "__init__.py", output / "src" / "__init__.py")
    shutil.copy2(ROOT / "src" / "multiplayer_net.py", output / "src" / "multiplayer_net.py")
    (output / "SERVER_SETUP.txt").write_text(
        """KILL ZONE MULTIPLAYER — DEDICATED SERVER SETUP

1. Upload and extract the CONTENTS of this bundle into /home/container.
   app.py must be located at /home/container/app.py.
2. Keep App py file set to app.py and Requirements file set to requirements.txt.
3. Assign the TCP allocation/port 25503 to the server.
4. Start the server. The console should print:
      KILL ZONE PVP SERVER 0.1.0
      Protocol 1 listening on ('0.0.0.0', 25503)
5. Players open Multiplayer in Kill Zone and connect to 88.99.98.156:25503.

The service is an early friends-only alpha. It is server-authoritative, but its
TCP transport is not encrypted and it has no account system yet.
""",
        encoding="utf-8",
    )


def write_zip(source: Path, destination: Path) -> None:
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(source.rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts and path.suffix not in (".pyc", ".pyo"):
                archive.write(path, path.relative_to(source))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "output",
        nargs="?",
        type=Path,
        default=ROOT / "build" / "dedicated_server",
    )
    parser.add_argument("--zip", action="store_true", dest="make_zip")
    args = parser.parse_args()
    output = args.output.resolve()
    build_server(output)
    print(f"Dedicated server materialized at {output}")
    if args.make_zip:
        destination = output.with_suffix(".zip")
        write_zip(output, destination)
        print(f"Dedicated server archive written to {destination}")


if __name__ == "__main__":
    main()
