"""Materialize a reviewable, single-file Kill Zone release directory."""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import zipfile

from src.source_loader import game_source, test_source


ROOT = Path(__file__).resolve().parent
RELEASE_MARKER = ".killzone-generated-release"
SUPPORT_FILES = (
    "README.md",
    "ASSET_SOURCES.md",
    "requirements.txt",
    "launch_kill_zone.bat",
    "run_self_test.bat",
    "validate.bat",
    "validate.py",
    "regression_test.py",
    "runtime_smoke_test.py",
    "stress_test.py",
    "benchmark.py",
)


def build_release(output: Path):
    if output.exists() and any(output.iterdir()):
        marker = output / RELEASE_MARKER
        if not marker.is_file():
            raise RuntimeError(f"Refusing to replace unmarked non-empty directory: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / RELEASE_MARKER).write_text("Generated by build_release.py\n", encoding="utf-8")
    (output / "kill_zone.py").write_text(game_source(ROOT), encoding="utf-8", newline="\n")
    (output / "self_test.py").write_text(test_source(ROOT, "self_test_v6.py.gz"), encoding="utf-8", newline="\n")
    (output / "ui_smoke_test.py").write_text(test_source(ROOT, "ui_smoke_v6.py.gz"), encoding="utf-8", newline="\n")
    for name in SUPPORT_FILES:
        shutil.copy2(ROOT / name, output / name)


def write_zip(source: Path, destination: Path):
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(source.rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts and path.suffix not in (".pyc", ".pyo"):
                archive.write(path, path.relative_to(source.parent))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("output", nargs="?", type=Path, default=ROOT / "build" / "kill_zone_release")
    parser.add_argument("--zip", action="store_true", dest="make_zip")
    args = parser.parse_args()
    output = args.output.resolve()
    build_release(output)
    print(f"Release materialized at {output}")
    if args.make_zip:
        destination = output.with_suffix(".zip")
        write_zip(output, destination)
        print(f"Release archive written to {destination}")


if __name__ == "__main__":
    main()
