"""Materialize a reviewable, single-file Kill Zone release directory."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from src.release_tools import recreate_generated_directory, write_zip
from src.source_loader import game_source, test_source

ROOT = Path(__file__).resolve().parent
RELEASE_MARKER = ".killzone-generated-release"
SUPPORT_FILES = (
    "README.md",
    "ASSET_SOURCES.md",
    "requirements.txt",
    "launch_kill_zone.bat",
    "validate.bat",
    "validate.py",
    "regression_test.py",
    "runtime_smoke_test.py",
    "multiplayer_test.py",
    "presentation_test.py",
    "combat2_test.py",
    "combat_polish_test.py",
    "stress_test.py",
    "benchmark.py",
)


def build_release(output: Path):
    recreate_generated_directory(
        output,
        RELEASE_MARKER,
        "Generated by build_release.py\n",
    )
    (output / "kill_zone.py").write_text(game_source(ROOT), encoding="utf-8", newline="\n")
    (output / "self_test.py").write_text(test_source(ROOT, "legacy_self_test.py.gz"), encoding="utf-8", newline="\n")
    (output / "ui_smoke_test.py").write_text(test_source(ROOT, "legacy_ui_smoke_test.py.gz"), encoding="utf-8", newline="\n")
    (output / "src").mkdir(exist_ok=True)
    shutil.copy2(ROOT / "src" / "__init__.py", output / "src" / "__init__.py")
    shutil.copy2(ROOT / "src" / "multiplayer_net.py", output / "src" / "multiplayer_net.py")
    (output / "multiplayer_server").mkdir(exist_ok=True)
    shutil.copy2(ROOT / "multiplayer_server" / "app.py", output / "multiplayer_server" / "app.py")
    shutil.copy2(
        ROOT / "multiplayer_server" / "requirements.txt",
        output / "multiplayer_server" / "requirements.txt",
    )
    for name in SUPPORT_FILES:
        shutil.copy2(ROOT / name, output / name)
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("output", nargs="?", type=Path, default=ROOT / "build" / "kill_zone_release")
    parser.add_argument("--zip", action="store_true", dest="make_zip")
    args = parser.parse_args()
    output = args.output.resolve()
    build_release(output)
    print(f"Release materialized at {output}")
    if args.make_zip:
        destination = output.with_suffix(".zip")
        write_zip(output, destination, include_root=True)
        print(f"Release archive written to {destination}")


if __name__ == "__main__":
    main()
